update workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,16 +1,22 @@
-name: Lighthouse
-on: push
+name: Build project and Run Lighthouse CI
+on: [push]
 jobs:
-  run-lighthouse:
+  lhci:
+    name: Lighthouse CI
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
-      - name: Build Site
+      - name: Use Node.js 10.x
+        uses: actions/setup-node@v1
+        with:
+          node-version: 10.x
+      - name: npm install, build
         run: |
           yarn install
           yarn build
-      - name: Run Lighthouse against a static build dir
-        uses: treosh/lighthouse-ci-action@v2
-        with:
-          # no urls needed, since it uses local folder to scan .html files
-          configPath: './lighthouserc.json'
+      - name: run Lighthouse CI
+        env:
+          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+        run: |
+          npm install -g @lhci/cli@0.3.x
+          lhci autorun || echo "LHCI failed!"
